export const Arithmetic = {
  "topic": "Arithmetic",
  "source": "Manhattan Prep – 5 lb. Book of GRE Practice Problems",
  "chapter": 7,
  "total_questions": 28,
  "quantitative_comparison_instructions": {
    "A": "Quantity A is greater.",
    "B": "Quantity B is greater.",
    "C": "The two quantities are equal.",
    "D": "The relationship cannot be determined from the information given."
  },
  "questions": [
    {
      "id": "arith_001",
      "number": 1,
      "type": "quantitative_comparison",
      "quantity_a": "$39 - (25 - 17)$",
      "quantity_b": "$39 - 25 - 17$",
      "answer": "A",
      "explanation": "## Order of Operations — Parentheses Change Everything\n\nThe only difference between the two quantities is the parentheses.\n\n**Quantity A:**\n$$39 - (25 - 17) = 39 - 8 = 31$$\n\n**Quantity B:**\n$$39 - 25 - 17 = 14 - 17 = -3$$\n\n---\n\n### Why They Differ\n\nDistributing the negative sign:\n$$39 - (25 - 17) = 39 - 25 + 17$$\n\nSo Quantity A **adds** $17$, while Quantity B **subtracts** it — a difference of $34$.\n\n$$31 > -3 \\implies \\boxed{A}$$",
    },
    {
      "id": "arith_002",
      "number": 2,
      "type": "quantitative_comparison",
      "quantity_a": "$14 - 3(4 - 6)$",
      "quantity_b": "$(4)(-3)(2)(-1)$",
      "answer": "B",
      "explanation": "## PEMDAS with Negative Numbers\n\n**Quantity A:**\n$$14 - 3(4 - 6)$$\nStep 1 — parentheses: $4 - 6 = -2$\n\nStep 2 — multiplication: $3 \\times (-2) = -6$\n\nStep 3 — subtraction: $14 - (-6) = 14 + 6 = 20$\n\n---\n\n**Quantity B — count negative signs:**\n$$(4)(-3)(2)(-1)$$\nTwo negatives $\\Rightarrow$ positive. Multiply magnitudes:\n$$4 \\times 3 \\times 2 \\times 1 = 24$$\n\n---\n\n$$24 > 20 \\implies \\boxed{B}$$",
    },
    {
      "id": "arith_003",
      "number": 3,
      "type": "quantitative_comparison",
      "quantity_a": "$-5 \\times 1 \\div 5$",
      "quantity_b": "$-6 \\times 1 \\div 6$",
      "answer": "C",
      "explanation": "## Recognising the Pattern\n\nBoth expressions have the structure $-n \\times 1 \\div n$:\n$$-n \\times \\frac{1}{n} = -\\frac{n}{n} = -1$$\n\n**Quantity A:** $-5 \\times 1 \\div 5 = -1$\n\n**Quantity B:** $-6 \\times 1 \\div 6 = -1$\n\n> Whenever you see $-n \\div n$, the result is always $-1$ (for $n \\neq 0$).\n\n$$-1 = -1 \\implies \\boxed{C}$$",

    },
    {
      "id": "arith_004",
      "number": 4,
      "type": "numeric_entry",
      "text": "What is the value of $5 - (4 - (3 - (2 - 1)))$?",
      "answer": "3",
      "explanation": "## Nested Parentheses — Work from the Inside Out\n\n**Layer 1 — innermost:** $2 - 1 = 1$\n\nExpression: $5 - (4 - (3 - 1))$\n\n**Layer 2:** $3 - 1 = 2$\n\nExpression: $5 - (4 - 2)$\n\n**Layer 3:** $4 - 2 = 2$\n\n**Final:** $5 - 2 = 3$\n\n---\n\n### Method 2 — Distribute All Signs\n$$5 - 4 + 3 - 2 + 1 = 3$$\n\n$$\\boxed{3}$$",

    },
    {
      "id": "arith_005",
      "number": 5,
      "type": "quantitative_comparison",
      "quantity_a": "$-\\left(\\dfrac{2^3}{2}\\right)$",
      "quantity_b": "$(-2)^2$",
      "answer": "B",
      "explanation": "## Exponents — Location of the Minus Sign Matters\n\n**Quantity A:**\n$$2^3 = 8 \\implies \\frac{8}{2} = 4 \\implies -(4) = -4$$\n\n**Quantity B:**\n$$(-2)^2 = (-2)(-2) = +4$$\n\n---\n\n### Key Rule\n$$-2^2 = -(2^2) = -4 \\qquad \\text{but} \\qquad (-2)^2 = +4$$\n\nParentheses around the base include the negative in the exponentiation.\n\n$$4 > -4 \\implies \\boxed{B}$$",
    },
    {
      "id": "arith_006",
      "number": 6,
      "type": "quantitative_comparison",
      "quantity_a": "$5^3 - 5^2$",
      "quantity_b": "$5$",
      "answer": "A",
      "explanation": "## Subtracting Powers — Never Subtract the Exponents\n\nA common mistake: $5^3 - 5^2 = 5^{3-2} = 5$. **This is wrong.**\n\n**Method 1 — Direct:**\n$$5^3 = 125,\\quad 5^2 = 25 \\implies 125 - 25 = 100$$\n\n**Method 2 — Factor:**\n$$5^3 - 5^2 = 5^2(5 - 1) = 25 \\times 4 = 100$$\n\n$$100 > 5 \\implies \\boxed{A}$$",

    },
    {
      "id": "arith_007",
      "number": 7,
      "type": "quantitative_comparison",
      "quantity_a": "$-10 - (-3)^2$",
      "quantity_b": "$-[10 + (-3)^2]$",
      "answer": "C",
      "explanation": "## Negative Signs Inside and Outside Brackets\n\nFirst resolve $(-3)^2 = 9$.\n\n**Quantity A:** $-10 - 9 = -19$\n\n**Quantity B:** $-[10 + 9] = -19$\n\n---\n\nDistribute the outer negative in B:\n$$-[10 + (-3)^2] = -10 - (-3)^2 = -10 - 9$$\n\nIdentical to A.\n\n$$-19 = -19 \\implies \\boxed{C}$$",
    },
    {
      "id": "arith_008",
      "number": 8,
      "type": "quantitative_comparison",
      "quantity_a": "$(30{,}000{,}000)(2{,}000{,}000)$",
      "quantity_b": "$(15{,}000{,}000)(4{,}000{,}000)$",
      "answer": "C",
      "explanation": "## Large Number Multiplication — Scientific Notation\n\n$$\\text{A} = (3 \\times 10^7)(2 \\times 10^6) = 6 \\times 10^{13}$$\n\n$$\\text{B} = (1.5 \\times 10^7)(4 \\times 10^6) = 6 \\times 10^{13}$$\n\n---\n\n**Spot the relationship:** From A to B, the first factor is halved ($30 \\to 15$) and the second is doubled ($2 \\to 4$). Halving and doubling cancel.\n\n$$6 \\times 10^{13} = 6 \\times 10^{13} \\implies \\boxed{C}$$",

    },
{
  "id": "arith_009",
  "number": 9,
  "type": "numeric_entry",
  "text": "What is the sum of the numbers in the grid?",
  "answer": "147",
  "image": "/Arithmetic/arith_009.svg",
  "explanation": "## Grid Sum — Exploit Symmetry\n\nIn each row the symmetric pairs cancel. Only the two rightmost columns contribute:\n\n| Row | Sum |\n|-----|-----|\n| 1 | $3 + 4 = 7$ |\n| 2 | $6 + 8 = 14$ |\n| 3 | $9 + 12 = 21$ |\n| 4 | $12 + 16 = 28$ |\n| 5 | $15 + 20 = 35$ |\n| 6 | $18 + 24 = 42$ |\n\n**Arithmetic series** $7, 14, 21, \\ldots, 42$ ($n=6$, $d=7$):\n$$S = \\frac{6}{2}(7 + 42) = 3 \\times 49 = 147$$\n\n$$\\boxed{147}$$",

},
    {
      "id": "arith_010",
      "number": 10,
      "type": "numeric_entry",
      "text": "Molly worked at an amusement park over the summer. Every two weeks, she was paid according to the following schedule: at the end of the first 2 weeks, she received $\\$160$. At the end of each subsequent 2-week period, she received $\\$1$, plus an additional amount equal to the sum of all payments she had received in previous weeks. How much money was Molly paid during the full 10 weeks of summer?",
      "answer": "2575",
      "explanation": "## Recursive Payment Schedule\n\n| Period | Payment | Cumulative |\n|--------|---------|------------|\n| Wk 1–2 | $\\$160$ | $\\$160$ |\n| Wk 3–4 | $\\$1 + \\$160 = \\$161$ | $\\$321$ |\n| Wk 5–6 | $\\$1 + \\$321 = \\$322$ | $\\$643$ |\n| Wk 7–8 | $\\$1 + \\$643 = \\$644$ | $\\$1{,}287$ |\n| Wk 9–10 | $\\$1 + \\$1{,}287 = \\$1{,}288$ | $\\$2{,}575$ |\n\n$$\\boxed{\\$2{,}575}$$",

    },
    {
      "id": "arith_011",
      "number": 11,
      "type": "quantitative_comparison",
                        

      "context": "A book with $80{,}000$ words costs $\\$24$ and a short story with $1{,}000$ words costs $\\$1$.",
      "quantity_a": "Cost per word of the book",
      "quantity_b": "Cost per word of the short story",
      "answer": "B",
      "explanation": "## Unit Rates — Cost Per Word\n\n**Book:** $\\dfrac{\\$24}{80{,}000} = \\$0.0003$ per word\n\n**Short story:** $\\dfrac{\\$1}{1{,}000} = \\$0.001$ per word\n\n---\n\nThe book costs $24\\times$ as much but has $80\\times$ as many words. Value ratio $= \\frac{24}{80} = 0.3 < 1$, so the book is cheaper per word.\n\n$$0.001 > 0.0003 \\implies \\boxed{B}$$",
  
    },
{
  "id": "arith_012",
  "number": 12,
  "type": "quantitative_comparison",
  "image": "/Arithmetic/arith_012.svg",
  "context": "**Ticket Prices at the Natural History Museum:**\n- Child (ages 5–18): Weekdays $\\$7$, Weekends & Holidays $\\$9$\n- Adult (ages 19–64): Weekdays $\\$14$, Weekends & Holidays $\\$16$\n- Senior (ages 65+): Weekdays $\\$8$, Weekends & Holidays $\\$10$\n- Children under 5: free",
  "quantity_a": "Price for one 12-year-old and one 39-year-old on a weekday",
  "quantity_b": "Price for one 4-year-old, two 8-year-olds, and one senior (65+) on a weekend, after a $\\$10$ coupon",
  "answer": "A",
  "explanation": "## Reading a Price Table\n\n**Quantity A — Weekday:**\n- 12-year-old (Child): $\\$7$\n- 39-year-old (Adult): $\\$14$\n$$\\text{Total} = \\$21$$\n\n**Quantity B — Weekend with coupon:**\n- 4-year-old (under 5): **free**\n- Two 8-year-olds: $2 \\times \\$9 = \\$18$\n- Senior: $\\$10$\n- Subtotal: $\\$28$; after $\\$10$ coupon: $\\$18$\n\n$$\\$21 > \\$18 \\implies \\boxed{A}$$",
},
    {
      "id": "arith_013",
      "number": 13,
      "type": "quantitative_comparison",
      "context": "On a certain train, tickets cost $\\$6$ each for children and $\\$9$ each for adults. The total train ticket cost for a group of six passengers was between $\\$44$ and $\\$50$.",
      "quantity_a": "The number of children in the group",
      "quantity_b": "The number of adults in the group",
      "answer": "D",
      "explanation": "## Finding Valid Combinations\n\nLet $c$ = children, $a = 6 - c$.\n$$T = 6c + 9(6-c) = 54 - 3c$$\n\nNeed $44 \\leq 54 - 3c \\leq 50$:\n$$\\frac{4}{3} \\leq c \\leq \\frac{10}{3} \\implies c \\in \\{2, 3\\}$$\n\n**Case $c = 3$, $a = 3$:** Equal → C\n\n**Case $c = 2$, $a = 4$:** B is greater\n\nTwo valid cases give different comparisons.\n\n$$\\boxed{D}$$",

    },
    {
      "id": "arith_014",
      "number": 14,
      "type": "multiple_choice",
      "text": "If $617$ is divided by $49$, the sum of the **tens digit** and the **tenths digit** of the resulting number is what value?",
      "options": {
        "A": "$1$",
        "B": "$5$",
        "C": "$6$",
        "D": "$7$",
        "E": "$9$"
      },
      "answer": "C",
      "explanation": "## Tens Digit vs. Tenths Digit\n\n$$617 \\div 49 = 12.591\\ldots$$\n\n$$\\underbrace{1}_{\\text{tens}}\\underbrace{2}_{\\text{ones}}.\\underbrace{5}_{\\text{tenths}}\\underbrace{9}_{\\text{hundredths}}\\ldots$$\n\n- **Tens digit** $= 1$\n- **Tenths digit** $= 5$\n\n$$1 + 5 = 6 \\implies \\boxed{C}$$",

    },
    {
      "id": "arith_015",
      "number": 15,
      "type": "quantitative_comparison",
      "quantity_a": "The number of days between May 30, 1917, and May 15, 1996, inclusive",
      "quantity_b": "The number of days between May 15, 1912, and May 30, 1991, inclusive",
      "answer": "B",
      "explanation": "## Comparing Date Spans\n\nBoth spans are $\\approx 79$ years. The key is the within-month direction.\n\n**Quantity A:** Starts May 30, ends May 15 — end is 15 days *earlier* → span $= 79$ years $- 15$ days\n\n**Quantity B:** Starts May 15, ends May 30 — end is 15 days *later* → span $= 79$ years $+ 15$ days\n\nB is longer by $\\approx 30$ days.\n\n$$\\boxed{B}$$",
    },
    {
      "id": "arith_016",
      "number": 16,
      "type": "quantitative_comparison",
      "context": "Alfred's Coffee Shop: buy six cups, get one free. Boris's Coffee Shop: 15% off orders of $6+$ cups. Regular price: $\\$2.60$/cup at both shops.",
      "quantity_a": "Total cost for 7 cups from Alfred's",
      "quantity_b": "Total cost for 7 cups from Boris's",
      "answer": "A",
      "explanation": "## Comparing Discount Structures\n\n**Alfred's** — pay for 6:\n$$6 \\times \\$2.60 = \\$15.60$$\nEffective discount: $\\frac{1}{7} \\approx 14.3\\%$\n\n**Boris's** — 15% off 7 cups:\n$$7 \\times \\$2.60 \\times 0.85 = \\$15.47$$\nEffective discount: $15\\%$\n\nBoris's 15% > Alfred's 14.3%, so Alfred's charges more.\n\n$$\\$15.60 > \\$15.47 \\implies \\boxed{A}$$",
    },
    {
      "id": "arith_017",
      "number": 17,
      "type": "multiple_choice",
      "text": "In a certain ancient kingdom, the standard unit of measure was the 'crown,' equal to $10$ standard modern inches. An alternative unit was the 'scepter,' equal to $14$ standard modern inches. If a tower measured $70$ crowns tall, how many scepters tall was it?",
      "options": {
        "A": "$35$",
        "B": "$49$",
        "C": "$50$",
        "D": "$75$",
        "E": "$98$"
      },
      "answer": "C",
      "explanation": "## Unit Conversion — Bridge Through a Common Unit\n\n**Step 1 — Crowns to inches:**\n$$70 \\times 10 = 700 \\text{ inches}$$\n\n**Step 2 — Inches to scepters:**\n$$700 \\div 14 = 50 \\text{ scepters}$$\n\n---\n\nSanity check: a scepter is longer than a crown, so scepters $< $ crowns. $50 < 70$ ✓\n\n$$\\boxed{C}$$",
    },
    {
      "id": "arith_018",
      "number": 18,
      "type": "numeric_entry",
      "text": "A total of $\\$450$ was donated to charity by $25$ employees. If $15$ employees donated at least $\\$12$ but less than $\\$19$ and $9$ employees donated at least $\\$19$, what is the maximum amount, in dollars, that the last employee could have donated?",
      "answer": "99",
      "explanation": "## Maximise One Value by Minimising All Others\n\n**Group 1** (15 employees, $\\$12$–$<\\$19$): minimum $= \\$12$ each\n$$15 \\times \\$12 = \\$180$$\n\n**Group 2** (9 employees, $\\geq\\$19$): minimum $= \\$19$ each\n$$9 \\times \\$19 = \\$171$$\n\n**Minimum for 24 employees:** $\\$180 + \\$171 = \\$351$\n\n**Maximum for 25th:** $\\$450 - \\$351 = \\$99$\n\n$$\\boxed{\\$99}$$",
    },
    {
      "id": "arith_019",
      "number": 19,
      "type": "numeric_entry",
      "text": "A tank has a capacity of $200$ pints. How many gallons of water would it take to fill the tank to $\\dfrac{3}{10}$ of its capacity? ($1$ gallon $= 8$ pints)",
      "answer": "7.5",
      "explanation": "## Fraction of Capacity + Unit Conversion\n\n**Step 1:**\n$$\\frac{3}{10} \\times 200 = 60 \\text{ pints}$$\n\n**Step 2:**\n$$60 \\div 8 = 7.5 \\text{ gallons}$$\n\n---\n\n**Method 2 — Convert capacity first:**\n$$200 \\div 8 = 25 \\text{ gallons} \\implies \\frac{3}{10} \\times 25 = 7.5$$\n\n$$\\boxed{7.5 \\text{ gallons}}$$",
    },
    {
      "id": "arith_020",
      "number": 20,
      "type": "quantitative_comparison",
      "context": "$1$ kilogram $= 2.2$ pounds",
      "quantity_a": "The number of kilograms in $44$ pounds",
      "quantity_b": "The number of pounds in $44$ kilograms",
      "answer": "B",
      "explanation": "## Unit Conversion — Direction Matters\n\n**A** (pounds → kg, divide):\n$$44 \\div 2.2 = 20 \\text{ kg}$$\n\n**B** (kg → pounds, multiply):\n$$44 \\times 2.2 = 96.8 \\text{ lb}$$\n\n> A kilogram is heavier than a pound: 44 lb = few kg; 44 kg = many lb.\n\n$$96.8 > 20 \\implies \\boxed{B}$$",
    },
    {
      "id": "arith_021",
      "number": 21,
      "type": "multiple_choice",
      "text": "If the formula for converting degrees Fahrenheit to degrees Celsius is $C = \\dfrac{5}{9}(F - 32)$, what is the value of $F$ when $C = 30$?",
      "options": {
        "A": "$-\\dfrac{10}{9}$",
        "B": "$\\dfrac{338}{9}$",
        "C": "$86$",
        "D": "$\\dfrac{558}{5}$",
        "E": "$112$"
      },
      "answer": "C",
      "explanation": "## Solving for the Input\n\nSubstitute $C = 30$:\n$$30 = \\frac{5}{9}(F - 32)$$\n\n**Step 1:** Multiply both sides by $\\dfrac{9}{5}$:\n$$30 \\times \\frac{9}{5} = F - 32 \\implies 54 = F - 32$$\n\n**Step 2:** $F = 54 + 32 = 86$\n\n**Verify:** $C = \\dfrac{5}{9}(86-32) = \\dfrac{5}{9}(54) = 30$ ✓\n\n$$\\boxed{C}$$",
    },
    {
      "id": "arith_022",
      "number": 22,
      "type": "numeric_entry",
      "text": "On a trip, Joe's car traveled an average of $36$ miles per gallon of fuel. Approximately how many kilometers did the car travel on $10$ liters of fuel?",
      "context": "$5$ miles $\\approx 8$ kilometres; $1$ gallon $\\approx 4$ litres",
      "answer": "144",
      "explanation": "## Chained Unit Conversion\n\n**Step 1 — miles/gallon → km/gallon:**\n$$36 \\times \\frac{8}{5} = 57.6 \\text{ km/gallon}$$\n\n**Step 2 — km/gallon → km/litre:**\n$$57.6 \\div 4 = 14.4 \\text{ km/litre}$$\n\n**Step 3 — multiply by litres:**\n$$14.4 \\times 10 = 144 \\text{ km}$$\n\n---\n\n**All at once:**\n$$36 \\times \\frac{8}{5} \\times \\frac{1}{4} \\times 10 = 36 \\times 4 = 144$$\n\n$$\\boxed{144 \\text{ km}}$$",
    },
    {
      "id": "arith_023",
      "number": 23,
      "type": "multiple_choice",
      "text": "How many $1$-inch square tiles would it take to cover the floor of a closet that has dimensions $5$ feet by $4$ feet? ($1$ foot $= 12$ inches)",
      "options": {
        "A": "$20$",
        "B": "$240$",
        "C": "$1{,}440$",
        "D": "$2{,}160$",
        "E": "$2{,}880$"
      },
      "answer": "E",
      "explanation": "## Area with Unit Conversion\n\n**Convert to inches first:**\n$$5 \\text{ ft} = 60 \\text{ in},\\quad 4 \\text{ ft} = 48 \\text{ in}$$\n\n**Area:**\n$$60 \\times 48 = 2{,}880 \\text{ in}^2$$\n\nEach tile $= 1 \\text{ in}^2$, so $\\mathbf{2{,}880}$ tiles.\n\n> **Trap A (20):** area in ft² — forgot to convert!\n\n$$\\boxed{E}$$",
    },
    {
      "id": "arith_024",
      "number": 24,
      "type": "quantitative_comparison",
      "context": "Child A ate $\\dfrac{3}{5}$ of a kilogram of chocolate. Child B ate $300$ grams. ($1$ kg $= 1{,}000$ g)",
      "quantity_a": "Weight in grams of chocolate Child A ate",
      "quantity_b": "Twice the weight in grams of chocolate Child B ate",
      "answer": "C",
      "explanation": "## Converting and Comparing\n\n**A:** $\\dfrac{3}{5} \\times 1{,}000 = 600$ g\n\n**B:** $2 \\times 300 = 600$ g\n\n$$600 = 600 \\implies \\boxed{C}$$",
    },
    {
      "id": "arith_025",
      "number": 25,
      "type": "multiple_choice",
      "text": "Out of $5.5$ billion bacteria grown for an experiment, $1$ in $75$ million has a particular mutation. Approximately how many of the bacteria have the mutation?",
      "options": {
        "A": "$7$",
        "B": "$73$",
        "C": "$733$",
        "D": "$7{,}333$",
        "E": "$73{,}333$"
      },
      "answer": "B",
      "explanation": "## Scientific Notation and Estimation\n\n$$\\frac{5.5 \\times 10^9}{75 \\times 10^6} = \\frac{5.5}{75} \\times 10^3$$\n\n$$\\frac{5.5}{75} \\approx 0.0733 \\implies 0.0733 \\times 10^3 \\approx 73$$\n\nAnswer choices differ by powers of $10$ — only order of magnitude matters. $\\frac{5.5}{75} < 1$ eliminates C, D, E. Between 7 and 73, our estimate $\\approx 73.3$ points clearly to B.\n\n$$\\boxed{B}$$",
    },
    {
      "id": "arith_026",
      "number": 26,
      "type": "multiple_choice",
      "text": "A particular nation's GDP is $\\$4.5$ billion. If the population is $1.75$ million, what is the per capita GDP, rounded to the nearest dollar?",
      "options": {
        "A": "$\\$3$",
        "B": "$\\$25$",
        "C": "$\\$257$",
        "D": "$\\$2{,}571$",
        "E": "$\\$25{,}714$"
      },
      "answer": "D",
      "explanation": "## Per Capita\n\n$$\\frac{4.5 \\times 10^9}{1.75 \\times 10^6} = \\frac{4.5}{1.75} \\times 10^3 = \\frac{18}{7} \\times 10^3 \\approx 2.571 \\times 10^3 = \\$2{,}571$$\n\n**Estimation:** $\\frac{4.5}{1.75} \\approx \\frac{4.5}{1.8} = 2.5$, so per capita $\\approx \\$2{,}500$. Only D is in this range.\n\n$$\\boxed{D}$$",
    },
    {
      "id": "arith_027",
      "number": 27,
      "type": "multiple_choice",
      "text": "Global GDP was $\\$69.97$ trillion in 2011. If the world population for 2011 was best estimated at $6{,}973{,}738{,}433$, approximately what was the global GDP per person?",
      "options": {
        "A": "$\\$10$",
        "B": "$\\$100$",
        "C": "$\\$1{,}000$",
        "D": "$\\$10{,}000$",
        "E": "$\\$100{,}000$"
      },
      "answer": "D",
      "explanation": "## Order of Magnitude Estimation\n\nRound aggressively (answers differ by $10\\times$):\n$$\\text{GDP} \\approx 7 \\times 10^{13},\\quad \\text{Population} \\approx 7 \\times 10^{9}$$\n\n$$\\frac{7 \\times 10^{13}}{7 \\times 10^{9}} = 10^4 = \\$10{,}000$$\n\n$$\\boxed{D}$$",
    },
    {
      "id": "arith_028",
      "number": 28,
      "type": "select_all",
      "text": "The runners on a cross country team ran a $5$-mile race at average speeds ranging from $4$ miles per hour to $7$ miles per hour, inclusive. Which of the following are possible race completion times for individual members of the team? Indicate all such times.",
      "options": [
        "$36$ minutes",
        "$48$ minutes",
        "$60$ minutes",
        "$75$ minutes",
        "$90$ minutes",
        "$120$ minutes"
      ],
      "answer": [
        "$48$ minutes",
        "$60$ minutes",
        "$75$ minutes"
      ],
      "explanation": "## Finding the Valid Time Range\n\nUse $\\text{Time} = \\dfrac{\\text{Distance}}{\\text{Speed}}$.\n\n**Fastest (7 mph) → shortest time:**\n$$t_{\\min} = \\frac{5}{7} \\times 60 \\approx 42.86 \\text{ min}$$\n\n**Slowest (4 mph) → longest time:**\n$$t_{\\max} = \\frac{5}{4} \\times 60 = 75 \\text{ min}$$\n\n**Valid range:** $42.86 \\leq t \\leq 75$\n\n| Time | Valid? |\n|------|--------|\n| $36$ min | ✗ too fast |\n| $48$ min | ✓ |\n| $60$ min | ✓ |\n| $75$ min | ✓ (boundary) |\n| $90$ min | ✗ too slow |\n| $120$ min | ✗ too slow |\n\n$$\\boxed{48,\\ 60,\\ 75 \\text{ minutes}}$$",
    }
  ]
}